### ISSUE TITLE
nitrogen8m-qt5-defconfig: x11.h error on gst1-plugins

### ISSUE THREAD

**Issue by xerdink** [boundarydevices/buildroot-external-boundary#4]
When building gst1-plugins-bad, there is `X11/xlib.h` not found error.

My host OS:
* Ubuntu 18.04

Hardware:
* Nitrogen8m

**Comment by gibsson** [comment]
Hi,
This is a known issue and patches have been submitted upstream waiting for approval.
If you feel like it, you can try applying those patches below and send "reviewed-by" replies to my patches on the mailing list:
http://patchwork.ozlabs.org/project/buildroot/list/?series=&submitter=66304&state=&q=&archive=&delegate=
Otherwise please wait for the official release to happen.
Regards,
Gary
